baseURL: https://cyr580.github.io/
languageCode: en-us
title: iLDesign
theme: HugoMDL

menu:
  # before: []
  # after:
  #   - name: Github
  #     url: https://github.com/wolanx
  #     weight: 10

params:
  # https://github.com/alex-shpak/hugo-book/blob/master/exampleSite/config.yaml
  BookDateFormat: "2006-01-02 15:04:05"

  BookRepo: https://github.com/cyr580/cyr580.github.io
  BookEditPath: edit/main
